# Development environment
FROM node:16

WORKDIR /app

ENV NODE_OPTIONS=--max_old_space_size=4096

# Install dependencies
COPY package.json ./
COPY sync-package-lock ./
RUN npm install --legacy-peer-deps
RUN npm install dotenv

# Add source files
COPY tsconfig.json ./
COPY nodemon.json ./
COPY src ./src
COPY database ./

# Compile TypeScript
RUN npm run build

# Setup migrations
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD [ "npm", "run", "serve" ]