# Development environment
FROM node:18-alpine

# Set app directory
WORKDIR /app

# Environment variables
ENV NODE_OPTIONS=--max_old_space_size=4096

# Install
COPY package.json ./
COPY sync-package-lock ./
RUN npm install --legacy-peer-deps && npm install -g knex

# Build
COPY nodemon.json ./
COPY tsconfig.json ./
COPY src ./src
COPY database ./database
COPY database/migrations ./database/migrations 
 # <-- Added this line
COPY __tests__ ./__tests__

# Entrypoint
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "npm", "run", "serve" ]