version: '3.8'

services:
  db:
    image: postgres:12
    container_name: postgres_db
    hostname: db  # Critical change
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5432"

  test:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    command: sh -c "npm install && npm run migrate:latest && npm test"
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}  # Must use 'db'
      # Remove DATABASE_HOST/DATABASE_PORT - they're conflicting
volumes:
  postgres_data: