# name: Docker Build and Push

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and Push Backend (Dev)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bmi-backend-dev:latest -f backend/Dockerfile.dev backend
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/bmi-backend-dev:latest

#       - name: Build and Push Frontend (Dev)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bmi-frontend-dev:latest -f frontend/Dockerfile.dev frontend
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/bmi-frontend-dev:latest



name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push Backend (Dev)
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bmi-backend-dev:latest
          
      - name: Build and Push Frontend (Dev)
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bmi-frontend-dev:latest