name: Docker Build and Push
on: push  # Triggers on every push to the repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dso101-frontend:latest -f Dockerfile.prod .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dso101-frontend:latest

      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dso101-backend:latest -f Dockerfile.prod .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dso101-backend:latest

      # Optional: Only needed if you're using a custom DB image
      - name: Build and Push Database
        run: |
          cd backend  # Assuming DB config is in backend/
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dso101-db:latest -f Dockerfile.db .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dso101-db:latest