name: Docker Build and Push
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend
        run: |
          cd frontend
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/dso101-frontend:latest \
            -f Dockerfile.prod \
            --push .

      - name: Build and Push Backend
        run: |
          cd backend
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/dso101-backend:latest \
            -f Dockerfile.prod \
            --push .